const labels = {
  evidence: 'Evidence',
  implication: 'Design implication',
};

const mediaSet = (slots, caption, video = '') => ({
  kind: 'media-set',
  slots,
  caption,
  video,
});

const figmaSlot = (file, options = {}) => ({
  file,
  src: `./assets/figma-exports/${file}`,
  ...options,
});

const rebuildAsset = (file) => `./assets/${file}`;

const currentDongScreens = {
  items: [
    { src: './assets/img-02.png', alt: 'Current Dong expense detail screen' },
    { src: './assets/img-03.png', alt: 'Current Dong summary screen' },
  ],
  caption: 'Existing Dong UI screenshots available in the repository.',
};

export const en = {
  meta: { locale: 'en', dir: 'ltr', languageLabel: 'English' },
  controls: {
    language: 'Language',
    theme: 'Theme',
    switchToEnglish: 'Switch to English',
    switchToPersian: 'Switch to Persian',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
  },
  hero: {
    eyebrow: 'Independent Product Design Case Study',
    productName: 'BluBank Dong',
    title: 'Turning Shared Expenses Into A Clear, Automated Flow.',
    subtitle: 'A proposed Dong experience that turns receipt capture, OCR review, and group splitting into one clearer flow.',
    meta: 'Parisa Nasri · Farnaz Toghiani · 2 Product Designers · Jun 2026',
    media: {
      video: './assets/figma-exports/hero-ocr-flow.mp4',
      alt: 'Final OCR flow preview for BluBank Dong',
      poster: { src: './assets/figma-exports/figma-ocr-final-breakdown.png', alt: 'Final OCR breakdown screen showing a clear editable group split' },
      caption: 'From receipt → to a clear, editable group split.',
    },
    evidenceLabel: 'Research evidence',
    scrollLabel: 'Explore the process',
    badges: [
      { label: '50+ app-store reviews' },
      { label: '4 user conversations' },
      { label: '85 heuristic checks' },
    ],
  },
  nav: {
    ariaLabel: 'Case study sections',
    items: [
      { id: 'overview', label: 'Overview' },
      { id: 'research', label: 'Research' },
      { id: 'insights', label: 'Insights' },
      { id: 'design', label: 'Design' },
      { id: 'iteration', label: 'Iteration' },
      { id: 'final', label: 'Final' },
    ],
  },
  context: {
    eyebrow: 'Context',
    title: 'Product, Role, And Users',
    lead: 'Dong is BluBank’s in-app group expense-splitting feature.',
    body: "BluBank is Iran's digital-only neobank. Dong helps friends, housemates, families, and travel groups track shared costs and settle up. Because money moves between people who already know each other, the experience has to protect trust, make owed amounts clear, and reduce the awkwardness of asking for repayment.",
    project: {
      kicker: 'Project context',
      title: 'Independent Product Design Case Study',
      disclosure: 'Independent product design case study — not affiliated with or commissioned by BluBank.',
      items: [
        { label: 'Designers', value: 'Parisa Nasri · Farnaz Toghiani' },
        { label: 'Team', value: '2 Product Designers' },
        { label: 'Date', value: 'Jun 2026' },
        { label: 'Research scope', value: '50+ reviews · 4 conversations · 85 heuristic checks' },
      ],
    },
  },
  currentExperience: {
    eyebrow: 'Current Dong experience',
    title: 'Dong Handles The Split, But Not The Work Around It',
    lead: 'Dong handles the split itself, but much of the work before and after the split still falls on the organizer.',
    label: 'Current Dong journey',
    screens: [
      { src: rebuildAsset('figma-exports/current-dong-balances.PNG'), alt: 'Current BluBank Dong group balances and outstanding transactions', caption: 'Current product evidence · group balances and manual reminders' },
      { src: rebuildAsset('figma-exports/current-dong-create-transaction.PNG'), alt: 'Current BluBank Dong transaction creation and manual split flow', caption: 'Current product evidence · create transaction and split manually' },
    ],
    steps: [
      { title: 'Track group balances', body: 'Users can see group transactions, payment progress, outstanding balances, and manually trigger reminders.' },
      { title: 'Create a transaction', body: 'Users create a shared transaction and enter the total amount.' },
      { title: 'Split manually', body: 'The amount is distributed among selected members, either equally or through manual amount editing.' },
    ],
    gap: {
      label: 'The gap',
      body: 'Dong handles the split — but the organizer still has to track, remind, and follow up manually.',
    },
  },
  problem: {
    eyebrow: 'Existing experience',
    title: 'The Core Problem Is Trust, Not Just Math',
    lead: 'The current flow explains why the redesign focuses on trust, clarity, and organizer effort.',
    asset: currentDongScreens,
    statement: {
      quote: 'Dong users who split expenses with friends and family are forced to manage critical parts of their workflow — calculating shares, documenting costs, and communicating about disputes — outside the app, because the feature lacks receipt support, flexible splitting, and cross-platform access. This fragmentation erodes trust between group members and creates enough friction that users abandon the feature for manual methods.',
      caption: 'Core problem statement.',
    },
    themes: [
      { title: 'Costs are hard to verify.', body: 'There is no receipt or documentation system inside the flow.' },
      { title: 'Splits are too manual.', body: 'Uneven shares, calculations, and repeated entries happen by hand.' },
      { title: 'Reminder support is limited.', body: 'Follow-up can fall back to individual manual reminders and personal chasing.' },
      { title: 'There is no automated settlement.', body: 'Participants still need to complete payment themselves; Automatic Payment is a proposed capability.' },
    ],
  },
  research: {
    eyebrow: 'Research',
    title: 'Documentation, Reminders, And Participation Kept Breaking The Flow',
    lead: 'I used four complementary methods to separate recurring complaints, human consequences, structural usability gaps, and comparable-product patterns.',
    snapshot: {
      ariaLabel: 'Research evidence snapshot',
      items: [
        { value: '50+', label: 'App-store reviews' },
        { value: '4', label: 'User conversations' },
        { value: '85', label: 'Heuristic checks' },
        { value: '5', label: 'Comparable products' },
      ],
    },
    methods: [
      {
        kicker: 'Desk Research · 50+ app-store reviews',
        title: 'Top complaints pointed to reminders, receipts, and Blu-only participation.',
        body: 'Reviews surfaced repeated frustration with tasks handled manually or outside Dong.',
        evidenceLabel: labels.evidence,
        evidence: '50+ app-store reviews.',
        implicationLabel: labels.implication,
        implication: 'Prioritize documentation, repayment support, and less brittle group participation.',
      },
      {
        kicker: 'User Interviews · 4 in-depth conversations',
        title: 'Users needed clarity before they could confidently pay.',
        body: 'Conversations clarified how those issues affect organizers and participants differently.',
        evidenceLabel: labels.evidence,
        evidence: '4 in-depth user conversations.',
        implicationLabel: labels.implication,
        implication: 'Make each charge understandable and reduce organizer effort.',
      },
      {
        kicker: 'Heuristic Evaluation · 85 checks',
        title: 'Flexibility and efficiency were the largest usability gap.',
        body: 'The usability review identified flexibility and efficiency as the biggest gap.',
        evidenceLabel: labels.evidence,
        evidence: '85 heuristic checks across Nielsen’s 10 heuristics.',
        implicationLabel: labels.implication,
        implication: 'Support faster, more flexible end-to-end expense handling.',
      },
    ],
    reviews: {
      kicker: 'MARKETPLACE EVIDENCE · 50+ REVIEWS',
      title: 'Reminders, Receipts, And Blu-only Participation Kept Reappearing',
      lead: "Reviews from Myket, Cafe Bazaar, and Koocheh pointed to three repeated complaint patterns.",
      evidenceLabel: 'Evidence',
      patternLabel: 'Recurring pattern',
      implicationLabel: 'Product implication',
      items: [
        { severity: 'High', severityTone: 'high', theme: 'Lack of smart debt reminders', evidence: 'User voice from 50+ app-store reviews.', pattern: 'Users forget to settle debts when reminders are not automatic or scheduled.', implication: 'Repayment support needs to reduce organizer follow-up without making the ask feel personal.' },
        { severity: 'High', severityTone: 'high', theme: 'No receipt intelligence', evidence: 'Repeated review pattern around manual entry and documentation gaps.', pattern: 'Manual entry and missing documentation made expenses harder to record and verify.', implication: 'Receipt/documentation support should make expenses easier to verify and explain.' },
        { severity: 'Medium', severityTone: 'medium', theme: 'Requirement to have a Blu account', evidence: 'Non-Blu participation appeared as a recurring marketplace complaint.', pattern: 'People in the social group but outside BluBank faced barriers to joining or settling.', implication: 'The barrier is real, but any response must respect likely product/business constraints.' },
      ],
    },
    interviews: {
      kicker: 'USER CONVERSATIONS · 4 PARTICIPANTS',
      title: 'The Complaints Mattered Because Shared Money Depends On Trust',
      lead: 'The conversations showed the human cost behind the reviews: uncertainty, extra organizer work, social discomfort, and harder group coordination.',
      items: [
        { title: '1. Transparency affects trust', insight: 'People wanted proof before they felt confident paying.', quotes: [{ text: 'If I could upload a receipt, it would be so much better.', source: 'Aram' }, { text: 'I have to send the receipt separately, outside the app.', source: 'Ali' }] },
        { title: '2. Manual work increases organizer effort', insight: 'Uneven splits pushed calculation and checking back onto the group.', quotes: [{ text: 'I have to manually enter unequal expenses myself.', source: 'Fereshteh' }, { text: 'Last time we just calculated everything manually between ourselves.', source: 'Mahnaz' }] },
        { title: '3. Reminders create social discomfort', insight: 'Following up felt personal, even when the debt itself was simple.', quotes: [{ text: "I have to remind each member individually, and I'm worried they'll think I'm deliberately pressuring them.", source: 'Fereshteh' }, { text: "It'd be better if a notification just went out automatically.", source: 'Aram' }] },
        { title: '4. Participation constraints complicate coordination', insight: 'Mixed Blu/non-Blu groups forced workarounds outside Dong.', quotes: [{ text: "If even one person doesn't have a Blu account, the entire flow breaks down.", source: 'Ali' }, { text: "Those who don't have Blu have to use card-to-card transfers through other banking apps.", source: 'Aram' }] },
      ],
    },
    competitive: {
      kicker: 'COMPARABLE PRODUCT ANALYSIS',
      title: 'Comparable Products Showed How These Situations Are Usually Supported',
      lead: 'Splitwise, Tricount, Monzo, Revolut, and Cino showed reusable patterns, not a checklist to copy.',
      gapLabel: 'Dong gap',
      items: [
        { title: 'Record and documentation', products: ['Splitwise', 'Tricount'], observation: 'Receipt scan, expense photos, calculators, and flexible allocation rules keep documentation inside the split.', gap: 'Dong leaves receipt documentation and flexible splitting work outside the flow.' },
        { title: 'Remind and explain', products: ['Splitwise', 'Monzo', 'Revolut'], observation: 'Automatic or system-mediated reminders reduce how much follow-up feels like a personal request.', gap: 'Dong still leans on manual organizer follow-up after the split.' },
        { title: 'Open network', products: ['Monzo', 'Cino'], observation: 'Guest links and secure payment links let people participate without fully joining the product first.', gap: 'Dong’s closed participation can block mixed Blu/non-Blu groups, but redesigning that model needs product constraint clarity.' },
      ],
      synthesis: 'Across the comparison, the opportunity areas were consistent: make expenses easier to document, reduce manual reminder pressure, support more flexible splitting, and treat non-Blu participation as a scoped product decision rather than an automatic redesign feature.',
    },
  },
  synthesis: {
    eyebrow: 'Research synthesis',
    title: 'Three Research Methods Pointed to the Same Three Problems',
    lead: 'Reviews revealed recurring complaints, interviews exposed the human friction behind them, and heuristic evaluation showed where the product created unnecessary work.',
    visual: {
      vennLabel: 'Cross-method convergence',
      sources: [
        { value: '50+', label: 'App-store Reviews' },
        { value: '4', label: 'User Conversations' },
        { value: '85', label: 'Heuristic Checks' },
      ],
      core: '3 shared\nproblems',
      problems: ['Manual follow-up', 'Missing receipt clarity', 'Blu-only participation'],
      headers: ['Problem', 'Desk Research', 'Interviews', 'Heuristic Eval'],
      rows: [
        { problem: 'No receipt / documentation system', desk: "Iran's app-store reviews", interviews: '3 / 4 requested it', heuristic: 'Flexibility gaps up to severity 4' },
        { problem: 'Manual-only split, reminders, calculations', desk: 'Top complaint pattern', interviews: '4 / 4 experienced this pain', heuristic: 'Multiple flexibility checks failed' },
        { problem: 'Closed BluBank-only ecosystem', desk: 'Repeated complaint pattern', interviews: 'Mentioned across conversations', heuristic: 'Flexibility gap rated severity 4' },
      ],
    },
    heuristic: {
      stats: [
        { value: '85', label: 'Check questions' },
        { value: '48%', label: 'Overall pass rate' },
        { value: '0–4', label: 'Nielsen severity scale' },
      ],
      chartTitle: 'Flexibility And Efficiency Were Dong’s Largest Usability Gaps',
      chartCaption: 'Priority score · issues × average severity',
      chartNote: 'One heuristic dominated the evaluation: H7 Flexibility & Efficiency.',
      bars: [
        { label: 'H7 · Flexibility & Efficiency', value: 100, score: '37', tone: 'crit' },
        { label: 'H10 · Help & Documentation', value: 21.6, score: '8', tone: 'warn' },
        { label: 'H3 · User Control & Freedom', value: 16.2, score: '6', tone: 'warn' },
        { label: 'H1 · Visibility of System Status', value: 13.5, score: '5', tone: 'warn' },
        { label: 'H5 · Error Prevention', value: 12.1, score: '4.5', tone: 'warn' },
        { label: 'H9 · Error Recovery', value: 10.2, score: '3.8', tone: 'warn' },
        { label: 'H8 · Aesthetic & Minimalist', value: 4, score: '1.5', tone: 'ok' },
        { label: 'H2 · Match System & Real World', value: 2.2, score: '.8', tone: 'ok' },
        { label: 'H6 · Recognition Not Recall', value: 1, score: '.4', tone: 'ok' },
        { label: 'H4 · Consistency & Standards', value: .6, score: '.2', tone: 'ok' },
      ],
      severity: {
        title: 'Severity distribution',
        caption: '85 checks rated 0 (no problem) to 4 (catastrophic).',
        items: [
          { label: '0 · Not a Problem', value: 100, count: '30', tone: 'ok' },
          { label: '1 · Cosmetic', value: 26.7, count: '8', tone: 'ok' },
          { label: '2 · Minor', value: 36.7, count: '11', tone: 'warn' },
          { label: '3 · Major', value: 70, count: '21', tone: 'warn' },
          { label: '4 · Catastrophic', value: 6.7, count: '2', tone: 'crit' },
        ],
      },
      passRate: {
        title: 'Pass rate by heuristic',
        caption: 'Share of checks passed within each heuristic.',
        items: [
          { label: 'H1 Visibility', value: 44, rate: '44%', tone: 'warn' },
          { label: 'H2 Real World', value: 60, rate: '60%', tone: 'warn' },
          { label: 'H3 Control', value: 33, rate: '33%', tone: 'crit' },
          { label: 'H4 Consistency', value: 100, rate: '100%', tone: 'ok' },
          { label: 'H5 Error Prev.', value: 50, rate: '50%', tone: 'warn' },
          { label: 'H6 Recognition', value: 83, rate: '83%', tone: 'ok' },
          { label: 'H7 Flexibility', value: 12, rate: '12%', tone: 'crit' },
          { label: 'H8 Aesthetic', value: 50, rate: '50%', tone: 'warn' },
          { label: 'H9 Recovery', value: 25, rate: '25%', tone: 'crit' },
          { label: 'H10 Help & Docs', value: 20, rate: '20%', tone: 'crit' },
        ],
      },
    },
  },
  insights: {
    eyebrow: 'Key insights',
    title: 'Four Design Priorities Came Out Of The Evidence',
    lead: 'The research pointed toward four product moves.',
    items: [
      { title: 'Transparency builds trust.', evidenceLabel: labels.evidence, evidence: '3 / 4 interviewees requested receipt or documentation support.', implicationLabel: labels.implication, implication: 'Use receipts, notes, and itemized breakdowns to make charges explainable.' },
      { title: 'Manual work creates abandonment risk.', evidenceLabel: labels.evidence, evidence: '4 / 4 interviewees experienced pain with manual splitting, reminders, or calculations.', implicationLabel: labels.implication, implication: 'Automate repeated steps while keeping the organizer in control.' },
      { title: 'Money reminders create social friction.', evidenceLabel: labels.evidence, evidence: 'Users described worry about pressuring friends when asking for repayment.', implicationLabel: labels.implication, implication: 'Make reminders neutral, system-supported, and less personally confrontational.' },
      { title: 'Closed participation limits group use.', evidenceLabel: labels.evidence, evidence: 'Non-Blu users appeared across interviews and as a top complaint in reviews.', implicationLabel: labels.implication, implication: 'Document external settlement as an opportunity, without redesigning BluBank membership.' },
    ],
  },
  personas: {
    eyebrow: 'Personas',
    title: 'Sara Organizes The Split; Nick Needs To Trust It',
    lead: 'Sara and Nick carry the same friction from two sides of the shared-expense relationship.',
    goalLabel: 'Goal',
    frictionLabel: 'Main friction',
    items: [
      {
        name: 'Sara',
        role: 'Organizer',
        image: { src: rebuildAsset('figma-exports/persona-sara.png'), alt: 'Sara, organizer persona from the original case study' },
        goal: 'Have Dong track the shared expense and reduce follow-up work.',
        friction: 'Manual expense entry, uneven splits, missing receipts, non-Blu members, and the work of reminding people herself.',
      },
      {
        name: 'Nick',
        role: 'Participant',
        image: { src: rebuildAsset('figma-exports/persona-nick.png'), alt: 'Nick, participant persona from the original case study' },
        goal: 'Understand exactly what he owes and pay on time.',
        friction: 'Limited transparency, missing supporting documentation, forgotten payments, and no clear way to question a share.',
      },
    ],
  },
  socialFriction: {
    eyebrow: 'The social friction problem',
    title: 'The Real Challenge Isn’t Splitting The Bill — It’s Asking For The Money.',
    lead: 'Unpaid debt can turn a product task into an interpersonal moment.',
    steps: [
      { title: 'Unpaid debt', body: 'A friend still owes money in the group.', image: { src: rebuildAsset('figma-exports/friction-1.png'), alt: 'Original illustration of an anxious payment reminder moment' } },
      { title: 'Hesitation', body: 'The organizer worries that reminding them will feel pushy or transactional.', image: { src: rebuildAsset('figma-exports/friction-2.png'), alt: 'Original illustration of hesitation before asking for repayment' } },
      { title: 'Personal chasing', body: 'Follow-up moves outside the product and into a direct personal ask.', image: { src: rebuildAsset('figma-exports/friction-3.png'), alt: 'Original illustration of a nervous repayment message' } },
      { title: 'Relationship friction', body: 'Repeating this pattern can quietly wear on the relationship.', image: { src: rebuildAsset('figma-exports/friction-4.png'), alt: 'Original illustration of relationship discomfort around debt' } },
    ],
    source: 'Based on user feedback patterns observed in comparable expense-splitting apps, and consistent with published research on interpersonal debt communication (Angulo, Goldstein & Norton, 2024, Journal of Consumer Psychology).',
  },
  journey: {
    eyebrow: 'Journey mapping',
    title: 'Trust Drops When Costs Become Manual, Unclear, And Personal',
    lead: 'One map of the whole Dong experience, synthesized across desk research, user interviews, and heuristic evaluation — not interview data alone.',
    arcLabel: 'Emotional arc for Sara and Nick across the current Dong journey',
    caption: 'Emotional Arc · Sara and Nick across the journey. Dashed segments show where a persona is not active in a step; red marks key opportunity points.',
    saraLabel: 'Sara · ',
    nickLabel: 'Nick · ',
    opportunityLabel: 'Opportunity',
    personas: [
      { name: 'Sara', role: 'Organizer', image: { src: rebuildAsset('figma-exports/persona-sara.png'), alt: 'Sara persona' } },
      { name: 'Nick', role: 'Participant', image: { src: rebuildAsset('figma-exports/persona-nick.png'), alt: 'Nick persona' } },
    ],
    columns: [
      { title: 'Set Up', sara: 'Starts a group for the shared expense and invites members.', nick: 'Joins the group through the invite link.', pains: ["Some intended members can't join without a Blu account."] },
      { title: 'Log & Split', sara: 'Manually logs each cost and splits the amount across the group.', nick: 'Not active in this step.', pains: ['Manual entry for every single cost adds up fast.', 'Uneven expenses require manual adjustment.', "Receipts and documentation can't be shared."] },
      { title: 'Track, Remind & Review', sara: "Shares the breakdown, tracks who's paid, and manually re-reminds unpaid members.", nick: "Reviews the charge assigned to him and decides whether it's correct before paying.", pains: ['Sara feels uncomfortable asking friends for money directly.', "Nick feels uncertain because receipts aren't attached."] },
      { title: 'Settling', sara: "Checks the group's debt/credit summary to see where payments and settlements stand.", nick: 'Completes the payment, Blu-to-Blu.', pains: ["Both see totals, but checking detail means opening transactions one by one."] },
    ],
    points: [
      { tone: 'sara', x: 12.5, y: 120, label: 'Sara · Frustrated', image: { src: rebuildAsset('figma-exports/emo-sara-frustrated.png'), alt: 'Sara feels frustrated at setup' } },
      { tone: 'nick', x: 12.5, y: 52, label: 'Nick · Curious', image: { src: rebuildAsset('figma-exports/emo-nick-curious.png'), alt: 'Nick feels curious at setup' } },
      { tone: 'sara', x: 37.5, y: 200, label: 'Sara · Overwhelmed', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-sara-overwhelmed.png'), alt: 'Sara feels overwhelmed at log and split' } },
      { tone: 'sara', x: 62.5, y: 160, label: 'Sara · Uncomfortable', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-sara-uncomfortable.png'), alt: 'Sara feels uncomfortable while reminding' } },
      { tone: 'nick', x: 62.5, y: 92, label: 'Nick · Uncertain', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-nick-uncertain.png'), alt: 'Nick feels uncertain while reviewing' } },
      { tone: 'sara', x: 81.5, y: 40, label: 'Sara · Relieved', image: { src: rebuildAsset('figma-exports/emo-sara-relieved.png'), alt: 'Sara feels relieved after settlement' } },
      { tone: 'nick', x: 88.7, y: 40, label: 'Nick · Relieved', image: { src: rebuildAsset('figma-exports/emo-nick-relieved.png'), alt: 'Nick feels relieved after settlement' } },
    ],
    tooltips: [
      { x: 12.5, y: 150, rows: [{ tone: 'sara', name: 'Sara', state: 'Frustrated' }, { tone: 'nick', name: 'Nick', state: 'Curious' }] },
      { x: 37.5, y: 232, rows: [{ tone: 'sara', name: 'Sara', state: 'Overwhelmed' }, { tone: 'nick', name: 'Nick', state: 'not involved', muted: true }] },
      { x: 62.5, y: 192, rows: [{ tone: 'sara', name: 'Sara', state: 'Uncomfortable' }, { tone: 'nick', name: 'Nick', state: 'Uncertain' }] },
      { x: 85, y: 72, rows: [{ tone: 'sara', name: 'Sara', state: 'Relieved' }, { tone: 'nick', name: 'Nick', state: 'Relieved' }] },
    ],
    legend: [
      { tone: 'sara', label: 'Sara' },
      { tone: 'nick', label: 'Nick' },
      { tone: 'inactive', label: 'Dashed = not involved' },
      { tone: 'opportunity', label: 'Opportunity = key friction / intervention point' },
    ],
  },
  opportunity: {
    eyebrow: 'Opportunity',
    title: 'From Evidence To Opportunity',
    label: 'How might we',
    question: 'How might Dong help groups document, split, and settle shared expenses with less manual effort and less social pressure?',
    body: 'This framing is derived from the recovered problem statement and converging research themes.',
  },
  prioritization: {
    matrix: {
      kicker: 'Prioritization',
      title: 'Four High-impact Opportunities Moved Into Design',
      body: 'OCR, itemized splitting, reminders, and automatic-payment exploration moved forward. Non-Blu participation stayed documented as a scope decision.',
      asset: {
        src: rebuildAsset('figma-exports/impact-effort-matrix-figma.png'),
        alt: 'Impact effort matrix exported from Figma node 721:24251',
      },
      focus: ['Receipt Scan / OCR', 'Flexible and itemized splitting', 'Reminder support', 'Automatic-payment exploration'],
    },
    items: [
      { title: 'Receipt Scan / OCR + Itemized Split', body: 'Prioritized because transparency and manual calculation gaps appeared across the evidence.' },
      { title: 'Reminder / Settlement', body: 'Prioritized because repayment follow-up is both a workflow issue and a social-friction issue.' },
      { title: 'Automatic Payment', body: 'Explored as a first-design flow to reduce repeated settlement effort; final constraints still need confirmation.' },
      { title: 'Non-Blu participation', body: 'Kept as an open opportunity until product constraints are clarified.' },
    ],
    nonBluDecision: {
      kicker: 'Product / scope decision',
      title: "Why we didn't design for non-Blu participation",
      body: 'We identified the barrier, but kept it outside the redesign scope. A plausible solution would mostly sit outside the in-app Dong flow: generate a debt/payment link or QR for the amount and share it through SMS or a link. Opening participation to non-Blu users could also conflict with BluBank’s likely acquisition incentives, so this opportunity was documented but not prioritized for the redesign.',
    },
  },
  productDirection: {
    eyebrow: 'Proposed product direction',
    title: 'The Redesign Focused On Three Proposed Capabilities',
    lead: 'These are proposed redesign capabilities, not current BluBank Dong features.',
    items: [
      {
        title: 'Receipt OCR',
        currentLabel: 'Current Dong',
        current: 'Transaction creation relies on amount entry and manual or equal share assignment.',
        gapLabel: 'Identified gap',
        gap: 'The product does not transform receipts into structured expenses or support item-level allocation.',
        proposedLabel: 'Proposed experience',
        proposed: 'Receipt scanning, OCR extraction, editable item review, discrepancy handling, and itemized member breakdown.',
      },
      {
        title: 'Reminder system',
        currentLabel: 'Current Dong',
        current: 'Outstanding transactions may require organizer follow-up and can expose manual individual reminders.',
        gapLabel: 'Identified gap',
        gap: 'There is no centralized reminder management, scheduling, recurrence, or richer reminder workflow.',
        proposedLabel: 'Proposed experience',
        proposed: 'A system-supported reminder experience designed to reduce interpersonal pressure and clarify settlement state.',
      },
      {
        title: 'Automatic Payment',
        currentLabel: 'Current Dong',
        current: 'Settlement depends on participants completing payment themselves.',
        gapLabel: 'Identified gap',
        gap: 'There is no automatic settlement rule for recurring or low-friction shared expenses.',
        proposedLabel: 'Proposed experience',
        proposed: 'Opt-in Automatic Payment with explicit activation, amount cap, consent, notification, clear status, and easy deactivation.',
      },
    ],
  },
  firstDesign: {
    eyebrow: 'Initial concepts',
    title: 'Design Concepts Turned Research Friction Into Flows',
    lead: 'Prioritization selected three capability areas to explore: receipt intelligence, reminder support, and Automatic Payment.',
    flows: [
      { title: 'Receipt Scan / OCR', hypothesis: 'If receipt details can be extracted and assigned clearly, payers can understand what they owe without extra explanation.', asset: mediaSet([figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }), figmaSlot('figma-ocr-edited-items.png', { node: '684:18532' }), figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' })], 'Concept exploration: extraction, editing, and discrepancy handling.') },
      { title: 'Reminder', hypothesis: 'If repayment follow-up feels system-supported, organizers can reduce awkward personal chasing.', asset: mediaSet([figmaSlot('figma-reminder-list.png', { node: '684:13311' }), figmaSlot('figma-reminder-schedule.png', { node: '684:13729' }), figmaSlot('figma-reminder-message.png', { node: '684:13859' })], 'Concept exploration: recipient selection, scheduling, and message review.') },
      { title: 'Automatic Payment', hypothesis: 'If repeated settlement steps can be simplified, groups may complete repayment with less manual effort.', asset: mediaSet([figmaSlot('figma-autopay-settings-entry.png', { node: '684:12288' }), figmaSlot('figma-autopay-limit.png', { node: '684:12380' }), figmaSlot('figma-autopay-refined.png', { node: '684:12480' })], 'Concept exploration: opt-in, amount limit, and active-state clarity.') },
    ],
  },
  feedback: {
    eyebrow: 'User feedback',
    title: 'User Feedback Exposed Three Clarity Gaps',
    lead: 'Three actionable findings from the Refactor notes shaped the final iteration.',
    items: [
      { feedbackLabel: 'User said', feedback: 'The completed reminder option was unclear: it did not communicate whether the debt was settled or only the reminder cycle had ended. Translated from Persian.', learnedLabel: 'What we learned', learned: 'Reminder status and debt status need to be visually and verbally distinct.', responseLabel: 'Design response', response: 'Clarify status language and separate reminder completion from settlement completion.' },
      { feedbackLabel: 'User said', feedback: 'The amount should be editable in an input too, not only controlled by a slider. Translated from Persian.', learnedLabel: 'What we learned', learned: 'A slider alone is not precise enough for a financial limit.', responseLabel: 'Design response', response: 'Add direct numeric input alongside the slider for exact control.' },
      { feedbackLabel: 'User said', feedback: 'The switch should be on when the feature is active and turn off when disabled. Translated from Persian.', learnedLabel: 'What we learned', learned: 'The toggle must follow the conventional ON/OFF mental model.', responseLabel: 'Design response', response: 'Align the automatic-payment switch with standard active/inactive behavior.' },
    ],
  },
  iteration: {
    eyebrow: 'Iteration',
    title: 'Each Iteration Turned Feedback Into A Clearer Control',
    lead: 'This is first design → user feedback → refined design, not existing BluBank → redesign.',
    beforeLabel: 'Before',
    afterLabel: 'After',
    items: [
      { title: 'Precise payment limit', v1: mediaSet([figmaSlot('figma-feedback-amount-before.png', { node: '684:15732' })]), v2: mediaSet([figmaSlot('figma-feedback-amount-after.png', { node: '684:15789' })]), issueLabel: 'User feedback', issue: 'A slider alone did not provide enough precision for a financial limit.', changeLabel: 'Design response', change: 'Allow direct numeric entry alongside the slider and clarify the label.' },
      { title: 'A clearer toggle mental model', v1: mediaSet([figmaSlot('figma-feedback-toggle-before.png', { node: '684:15996' })]), v2: mediaSet([figmaSlot('figma-feedback-toggle-after.png', { node: '684:16124' })]), issueLabel: 'User feedback', issue: 'The negative “Disable Automatic Payment” control reversed the expected switch mental model.', changeLabel: 'Design response', change: 'Use a positive “Automatic Payment” label: ON = active, OFF = inactive.' },
      { title: 'Clear reminder status', v1: mediaSet([figmaSlot('figma-feedback-reminder-before.png', { node: '684:16641' })]), v2: mediaSet([figmaSlot('figma-feedback-reminder-after.png', { node: '684:16729' })]), issueLabel: 'User feedback', issue: '“Completed reminder” did not clearly communicate whether the debt was settled or only the reminder process had ended.', changeLabel: 'Design response', change: 'Separate debt status from reminder status so completion is unambiguous.' },
    ],
  },
  ocrDecision: {
    eyebrow: 'Design decision',
    title: 'OCR Needed Automation With Human Control',
    lead: 'The OCR flow is a product-design rationale, not a fabricated feedback problem.',
    kicker: 'Receipt Scan / OCR',
    body: 'OCR can reduce manual entry, but financial flows still need review, correction, and explicit confirmation.',
    asset: mediaSet([
      figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }),
      figmaSlot('figma-ocr-edited-items.png', { node: '684:18532' }),
      figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' }),
      figmaSlot('figma-ocr-final-breakdown.png', { node: '684:19614' }),
    ], 'OCR decision flow: extract, edit, resolve discrepancy, confirm breakdown.'),
    points: [
      'OCR extracts receipt items and prices.',
      'Users review detected data and can edit, delete, or manually add items.',
      'The system compares edited item totals with the original receipt amount.',
      'If totals diverge, a discrepancy warning lets users correct items or intentionally continue.',
      'Before submission, users see each member’s share and can attach the receipt to the Dong transaction.',
    ],
  },
  finalExperience: {
    eyebrow: 'Final experience',
    title: 'The Final Experience Makes Shared Expenses Documented, Flexible, And System-supported',
    lead: 'Three proposed flows carry the redesign: OCR, neutral reminders, and opt-in Automatic Payment.',
    items: [
      { title: 'Final Flow 01 — OCR', outcome: 'Scan → Extract → Review → Assign → Confirm.', annotations: ['Receipt evidence stays attached.', 'Detected items remain editable.', 'The final split is confirmed before sharing.'], asset: mediaSet([figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }), figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' }), figmaSlot('figma-ocr-final-breakdown.png', { node: '684:19614' })], 'OCR turns a receipt into an editable, explainable group split.', 'final-ocr-flow.mp4') },
      { title: 'Final Flow 02 — Reminder', outcome: 'Centralized follow-up with scheduling, editable messages, and visible status history.', annotations: ['Recipient selection is centralized.', 'Reminders can be scheduled or recurring.', 'Message and history stay editable and visible.'], asset: mediaSet([figmaSlot('figma-reminder-list.png', { node: '684:13311' }), figmaSlot('figma-reminder-schedule.png', { node: '684:13729' }), figmaSlot('figma-reminder-message.png', { node: '684:13859' }), figmaSlot('figma-reminder-details.png', { node: '684:14264' })], 'System-supported reminders reduce direct personal chasing.', 'final-reminder-flow.mp4') },
      { title: 'Final Flow 03 — Automatic Payment', outcome: 'Opt-in settlement support with clear consent, caps, status, and easy deactivation.', annotations: ['Explicit opt-in and configurable cap.', 'Positive ON/OFF mental model.', 'System feedback confirms the state.'], asset: mediaSet([figmaSlot('figma-autopay-settings-entry.png', { node: '684:12288' }), figmaSlot('figma-autopay-limit.png', { node: '684:12380' }), figmaSlot('figma-autopay-refined.png', { node: '684:12480' }), figmaSlot('figma-autopay-success.png', { node: '684:12444' })], 'Automatic Payment remains opt-in, capped, and reversible.', 'final-auto-payment-flow.mp4') },
    ],
  },
  comparison: {
    eyebrow: 'Before / after',
    title: 'Manual And Opaque → Documented And System-supported',
    lead: 'The proposed direction shifts the work from organizer memory and personal follow-up into clearer product support.',
    beforeLabel: 'Before',
    afterLabel: 'Proposed experience',
    arrow: '→',
    before: ['Manual entry', 'Opaque charges', 'Organizer-driven follow-up'],
    after: ['Receipt evidence', 'Editable itemized split', 'System-supported settlement'],
  },
  measurement: {
    eyebrow: 'Measurement',
    title: 'What We Would Measure',
    lead: 'This project was not launched, so these are proposed success measures rather than measured outcomes.',
    items: [
      { title: 'OCR correction success', body: 'Can organizers catch and correct extracted receipt items before sharing?' },
      { title: 'Itemized split comprehension', body: 'Do payers understand what they owe and why before paying?' },
      { title: 'Reminder tone and clarity', body: 'Do reminders feel clear and neutral rather than personally confrontational?' },
      { title: 'Automatic-payment trust', body: 'Do caps, status, and deactivation controls make opt-in settlement feel safe?' },
    ],
  },
  reflection: {
    eyebrow: 'Reflection',
    title: 'Closing Reflection',
    lead: 'This was not launched, so the case closes with design learning and validation questions rather than impact claims.',
    learned: [
      { title: 'Shared money is social.', body: 'The hardest part is not only calculating the split; it is preserving trust between people.' },
      { title: 'Evidence needs to stay attached.', body: 'Receipts, notes, and itemization are not extras; they are how the group understands the expense.' },
    ],
    next: [
      { title: 'Validate with users.', body: 'Test the redesigned flows before claiming outcomes.' },
      { title: 'Clarify constraints.', body: 'Confirm automatic payment and non-Blu participation constraints before finalizing those flows.' },
    ],
  },
};
