const labels = {
  evidence: 'Evidence',
  implication: 'Design implication',
};

const mediaSet = (slots, caption, video = '') => ({
  kind: 'media-set',
  slots,
  caption,
  video,
});

const englishFigmaAssets = new Set([
  'figma-autopay-limit-en.png',
  'figma-autopay-refined-en.png',
  'figma-autopay-settings-entry-en.png',
  'figma-feedback-amount-after-en.png',
  'figma-feedback-amount-before-en.png',
  'figma-feedback-reminder-after-en.png',
  'figma-feedback-reminder-before-en.png',
  'figma-feedback-toggle-after-en.png',
  'figma-feedback-toggle-before-en.png',
  'figma-ocr-discrepancy-en.png',
  'figma-ocr-edited-items-en.png',
  'figma-ocr-extracted-items-en.png',
  'figma-ocr-final-breakdown-en.png',
  'figma-reminder-list-en.png',
  'figma-reminder-message-en.png',
  'figma-reminder-schedule-en.png',
]);

const localizedFigmaFile = (file) => {
  const englishFile = file.replace(/\.png$/i, '-en.png');
  return englishFigmaAssets.has(englishFile) ? englishFile : file;
};

const figmaSlot = (file, options = {}) => ({
  file,
  src: `./assets/figma-exports/${localizedFigmaFile(file)}`,
  ...options,
});

const rebuildAsset = (file) => `./assets/${file}`;

export const en = {
  meta: { locale: 'en', dir: 'ltr', languageLabel: 'English' },
  controls: {
    skipToMain: 'Skip to main content',
    language: 'Language',
    theme: 'Theme',
    switchToEnglish: 'Switch to English',
    switchToPersian: 'Switch to Persian',
    switchToLight: 'Switch to light mode',
    switchToDark: 'Switch to dark mode',
    backToTop: 'Back to the top',
  },
  hero: {
    eyebrow: 'Independent Product Design Case Study',
    productName: 'BluBank Dong',
    title: 'Turning <span class="hero-title-accent">Shared Expenses</span> Into A Clear, Automated Flow.',
    subtitle: 'A proposed Dong experience that turns receipt capture, OCR review, and group splitting into one clearer flow.',
    team: {
      ariaLabel: 'Project team: 3 Product Designers and 1 Mentor',
      label: '3 Product Designers · 1 Mentor',
      meta: 'Collaborative case study · Jun 2026',
      designers: [
        { src: './assets/team/designer-1.png' },
        { src: './assets/team/designer-2.png' },
        { src: './assets/team/designer-3.png' },
      ],
      mentor: { src: './assets/team/mentor.png' },
    },
    media: {
      video: './assets/figma-exports/hero-ocr-flow-en.mp4',
      alt: 'Final OCR flow preview for BluBank Dong',
      poster: { src: './assets/figma-exports/figma-ocr-final-breakdown-en.png', alt: 'Final OCR breakdown screen showing a clear editable group split' },
      caption: 'From receipt → to a clear, editable group split.',
    },
    evidenceLabel: 'Research evidence',
    scrollLabel: 'Explore the process',
    finalLabel: 'View final flows',
    actionsLabel: 'Case study shortcuts',
    badges: [
      { label: '50+ app-store reviews' },
      { label: '4 user conversations' },
      { label: '85 heuristic checks' },
    ],
  },
  quickScan: {
    eyebrow: 'Case Study at a Glance',
    title: 'Dong Splits The Bill — The Redesign Supports Everything Around It',
    lead: 'For a fast review, the story is problem → evidence → design response → honest project status.',
    items: [
      { label: 'Problem', body: 'Dong splits the amount, but organizers still document, calculate, remind, and follow up manually.', href: 'overview' },
      { label: 'Evidence', body: '50+ reviews, 4 user conversations, and 85 heuristic checks converged on trust, clarity, and effort.', href: 'research' },
      { label: 'Design response', body: 'Receipt OCR, itemized splitting, system-supported reminders, and opt-in Automatic Payment.', href: 'final' },
      { label: 'Project status', body: 'Independent, unlaunched concept with proposed success measures — no fabricated impact claims.', href: 'final' },
    ],
  },
  nav: {
    ariaLabel: 'Case study sections',
    items: [
      { id: 'overview', label: 'Overview' },
      { id: 'research', label: 'Research' },
      { id: 'insights', label: 'Insights' },
      { id: 'design', label: 'Design' },
      { id: 'iteration', label: 'Iteration' },
      { id: 'final', label: 'Final' },
    ],
  },
  context: {
    eyebrow: 'Product overview',
    title: 'Dong Brings Shared Expense Tracking Into BluBank',
    lead: 'Dong is BluBank’s in-app shared-expense feature for friends, families, housemates, and travel groups. It helps groups track costs, see who owes what, and settle balances.',
    body: 'Dong helps friends, housemates, families, and travel groups track shared costs, see who owes what, and settle balances.',
    bridge: 'The split is covered. Documentation, follow-up, and settlement management are not.',
    relationship: {
      ariaLabel: 'BluBank contains Dong, which supports shared expenses for groups',
      items: [
        { icon: 'bank', title: 'BluBank', caption: 'Digital bank' },
        { icon: 'split', title: 'Dong', caption: 'Shared expenses' },
        { icon: 'groups', title: 'Groups', caption: 'Track · Split · Settle' },
      ],
    },
    project: {
      kicker: 'BluBank at a glance',
      title: 'The Product Behind Dong',
      disclosure: 'Public company context · Independent case study, not affiliated with or commissioned by BluBank.',
      items: [
        { label: 'Founded', value: '2020' },
        { label: 'Powered by', value: 'Saman Bank' },
        { label: 'Users · May 2025', value: '≈14M' },
        { label: 'Employees', value: '501–1,000' },
      ],
    },
  },
  currentExperience: {
    eyebrow: 'Current experience',
    title: 'Dong Handles The Split, But Not The Work Around It',
    lead: 'Dong handles the split itself, but much of the work before and after the split still falls on the organizer.',
    label: 'Current Dong experience',
    screens: [
      { src: rebuildAsset('figma-exports/current-dong-balances-en.png'), alt: 'Current BluBank Dong group balances and outstanding transactions', caption: 'Balances & manual reminders' },
      { src: rebuildAsset('figma-exports/current-dong-create-transaction-en.png'), alt: 'Current BluBank Dong transaction creation and manual split flow', caption: 'Create transaction & split' },
    ],
    steps: [
      { title: 'Track group balances', body: 'Users can see group transactions, payment progress, outstanding balances, and manually trigger reminders.' },
      { title: 'Create a transaction', body: 'Users create a shared transaction and enter the total amount.' },
      { title: 'Split manually', body: 'The amount is distributed among selected members, either equally or through manual amount editing.' },
    ],
    gap: {
      label: 'The gap',
      body: 'Dong handles the split — but the organizer still has to track, remind, and follow up manually.',
    },
    summary: {
      kicker: 'Workflow handoff',
      title: 'Dong Supports The Split—Then Hands The Hard Work Back To The Organizer',
      ariaLabel: 'Where the shared-expense workflow leaves Dong and becomes manual work',
      stages: [
        { icon: 'product', tone: 'supported', eyebrow: 'Inside Dong', title: 'Product-supported', items: ['Track balances', 'Create an expense', 'Split shares'] },
        { icon: 'handoff', tone: 'manual', eyebrow: 'Where work leaves the product', title: 'Organizer-managed', items: ['Capture the receipt', 'Calculate exceptions', 'Remind & reconcile'] },
        { icon: 'impact', tone: 'impact', eyebrow: 'What the group experiences', title: 'Trust cost', items: ['More organizer effort', 'Less shared clarity', 'Lower group trust'] },
      ],
    },
  },
  research: {
    eyebrow: 'Research',
    title: 'Three Evidence Streams Converged On Receipt Clarity, Manual Follow-up, And Closed Participation',
    lead: 'We triangulated 50+ app-store reviews, 4 user conversations, and 85 heuristic checks. Each method revealed a different layer: frequency, human impact, and usability severity.',
    snapshot: {
      ariaLabel: 'Research evidence snapshot',
      items: [
        { value: '50+', label: 'App-store reviews' },
        { value: '4', label: 'User conversations' },
        { value: '85', label: 'Heuristic checks' },
        { value: '5', label: 'Comparable products' },
      ],
    },
    methods: [
      {
        kicker: 'Desk Research · 50+ app-store reviews',
        title: 'Top complaints pointed to reminders, receipts, and Blu-only participation.',
        body: 'Reviews surfaced repeated frustration with tasks handled manually or outside Dong.',
        evidenceLabel: labels.evidence,
        evidence: '50+ app-store reviews.',
        implicationLabel: labels.implication,
        implication: 'Prioritize documentation, repayment support, and less brittle group participation.',
      },
      {
        kicker: 'User Interviews · 4 in-depth conversations',
        title: 'Users needed clarity before they could confidently pay.',
        body: 'Conversations clarified how those issues affect organizers and participants differently.',
        evidenceLabel: labels.evidence,
        evidence: '4 in-depth user conversations.',
        implicationLabel: labels.implication,
        implication: 'Make each charge understandable and reduce organizer effort.',
      },
      {
        kicker: 'Heuristic Evaluation · 85 checks',
        title: 'Flexibility and efficiency were the largest usability gap.',
        body: 'The usability review identified flexibility and efficiency as the biggest gap.',
        evidenceLabel: labels.evidence,
        evidence: '85 heuristic checks across Nielsen’s 10 heuristics.',
        implicationLabel: labels.implication,
        implication: 'Support faster, more flexible end-to-end expense handling.',
      },
    ],
    reviews: {
      kicker: 'MARKETPLACE EVIDENCE · 50+ REVIEWS',
      title: 'Three Complaints Kept Reappearing',
      lead: 'Reviews from Myket, Cafe Bazaar, and Koocheh established frequency.',
      evidenceLabel: 'Evidence',
      patternLabel: 'Recurring pattern',
      implicationLabel: 'Product implication',
      items: [
        { severity: 'High', severityTone: 'high', theme: 'Manual reminders', evidence: 'User voice from 50+ app-store reviews.', pattern: 'Without system reminders, organizers had to chase repayment.', implication: 'Repayment support needs to reduce organizer follow-up without making the ask feel personal.' },
        { severity: 'High', severityTone: 'high', theme: 'No receipt support', evidence: 'Repeated review pattern around manual entry and documentation gaps.', pattern: 'Expenses were harder to record, verify, and explain.', implication: 'Receipt/documentation support should make expenses easier to verify and explain.' },
        { severity: 'Medium', severityTone: 'medium', theme: 'Blu-only participation', evidence: 'Non-Blu participation appeared as a recurring marketplace complaint.', pattern: 'Mixed groups had to settle outside Dong.', implication: 'The barrier is real, but any response must respect likely product/business constraints.' },
      ],
    },
    interviews: {
      kicker: 'USER CONVERSATIONS · 4 PARTICIPANTS',
      title: 'The Complaints Mattered Because Shared Money Depends On Trust',
      lead: 'The conversations showed the human cost behind the reviews: uncertainty, extra organizer work, social discomfort, and harder group coordination.',
      items: [
        { title: '1. No Transparency, No Trust', insight: 'People wanted proof before they felt confident paying.', quotes: [{ text: 'If I could upload a receipt, it would be so much better.', source: 'Participant 01', avatar: '1' }, { text: 'I have to send the receipt separately, outside the app.', source: 'Participant 02', avatar: '2' }] },
        { title: '2. Manual work increases organizer effort', insight: 'Uneven splits pushed calculation and checking back onto the group.', quotes: [{ text: 'I have to manually enter unequal expenses myself.', source: 'Participant 03', avatar: '3' }, { text: 'Last time we just calculated everything manually between ourselves.', source: 'Participant 04', avatar: '4' }] },
        { title: '3. Reminders create social discomfort', insight: 'Following up felt personal, even when the debt itself was simple.', quotes: [{ text: "I have to remind each member individually, and I’m worried they’ll think I’m deliberately pressuring them.", source: 'Participant 03', avatar: '3' }, { text: "It’d be better if a notification just went out automatically.", source: 'Participant 01', avatar: '1' }] },
        { title: '4. Non-Blu Users Break the Flow', insight: 'Mixed Blu/non-Blu groups forced workarounds outside Dong.', quotes: [{ text: "If even one person doesn’t have a Blu account, the entire flow breaks down.", source: 'Participant 02', avatar: '2' }, { text: "Those who don’t have Blu have to use card-to-card transfers through other banking apps.", source: 'Participant 04', avatar: '4' }] },
      ],
    },
    competitive: {
      kicker: 'COMPARABLE PRODUCT ANALYSIS',
      title: 'Competitors Solve the Math, Dong Needs to Solve the Experience.',
      lead: 'Splitwise, Tricount, Monzo, Revolut, and Cino showed reusable patterns, not a checklist to copy.',
      gapLabel: 'Dong gap',
      items: [
        { title: 'Record and documentation', products: ['Splitwise', 'Tricount'], observation: 'Receipt scan, expense photos, calculators, and flexible allocation rules keep documentation inside the split.', gap: 'Dong leaves receipt documentation and flexible splitting work outside the flow.' },
        { title: 'Remind and explain', products: ['Revolut', 'Splitwise', 'Monzo'], observation: 'Automatic or system-mediated reminders reduce how much follow-up feels like a personal request.', gap: 'Dong still leans on manual organizer follow-up after the split.' },
        { title: 'Open network', products: ['Monzo', 'Cino'], observation: 'Guest links and secure payment links let people participate without fully joining the product first.', gap: 'Dong’s closed participation can block mixed Blu/non-Blu groups, but redesigning that model needs product constraint clarity.' },
      ],
    },
  },
  synthesis: {
    eyebrow: 'Research synthesis',
    title: 'Three Research Methods Pointed to the Same Three Problems',
    lead: 'Reviews revealed recurring complaints, interviews exposed the human friction behind them, and heuristic evaluation showed where the product created unnecessary work.',
    visual: {
      vennLabel: 'Cross-method convergence',
      sources: [
        { value: '50+', label: 'App-store Reviews' },
        { value: '4', label: 'User Conversations' },
        { value: '85', label: 'Heuristic Checks' },
      ],
      core: '3 shared\nproblems',
      problems: ['Manual follow-up', 'Missing receipt clarity', 'Blu-only participation'],
      headers: ['Problem', 'Desk Research', 'Interviews', 'Heuristic Eval'],
      rows: [
        { problem: 'No receipt / documentation system', desk: "Iran's app-store reviews", interviews: '3 / 4 requested it', heuristic: 'Flexibility gaps up to severity 4' },
        { problem: 'Manual-only split, reminders, calculations', desk: 'Top complaint pattern', interviews: '4 / 4 experienced this pain', heuristic: 'Multiple flexibility checks failed' },
        { problem: 'Closed BluBank-only ecosystem', desk: 'Repeated complaint pattern', interviews: 'Mentioned across conversations', heuristic: 'Flexibility gap rated severity 4' },
      ],
    },
    heuristic: {
      eyebrow: 'Heuristic evaluation · 85 check questions',
      title: 'Too Much Manual Work, Not Enough Flexibility',
      lead: '85 check questions across Nielsen’s 10 usability heuristics, each issue rated on the 0–4 severity scale.',
      stats: [
        { value: '85', label: 'Check questions' },
        { value: '48%', label: 'Overall pass rate' },
        { value: '0–4', label: 'Nielsen severity scale' },
      ],
      focus: {
        title: 'Only 12% Of Flexibility Checks Passed—Dong’s Clearest Usability Gap',
        caption: 'Pass rate · four most critical heuristics',
        note: 'Flexibility and efficiency failed most often and carried the highest priority score: 37.',
        items: [
          { label: 'H7 · Flexibility & Efficiency', value: 12, rate: '12%', tone: 'crit', dominant: true },
          { label: 'H10 · Help & Documentation', value: 20, rate: '20%', tone: 'crit' },
          { label: 'H9 · Error Recovery', value: 25, rate: '25%', tone: 'crit' },
          { label: 'H3 · User Control & Freedom', value: 33, rate: '33%', tone: 'warn' },
        ],
      },
      disclosureLabel: 'View full heuristic evaluation · all 10 heuristics',
      chartTitle: 'Flexibility And Efficiency Were Dong’s Largest Usability Gaps',
      chartCaption: 'Priority score · issues × average severity',
      chartNote: 'One heuristic dominated the evaluation: H7 Flexibility & Efficiency.',
      bars: [
        { label: 'H7 · Flexibility & Efficiency', value: 100, score: '37', tone: 'crit' },
        { label: 'H10 · Help & Documentation', value: 21.6, score: '8', tone: 'warn' },
        { label: 'H3 · User Control & Freedom', value: 16.2, score: '6', tone: 'warn' },
        { label: 'H1 · Visibility of System Status', value: 13.5, score: '5', tone: 'warn' },
        { label: 'H5 · Error Prevention', value: 12.1, score: '4.5', tone: 'warn' },
        { label: 'H9 · Error Recovery', value: 10.2, score: '3.8', tone: 'warn' },
        { label: 'H8 · Aesthetic & Minimalist', value: 4, score: '1.5', tone: 'ok' },
        { label: 'H2 · Match System & Real World', value: 2.2, score: '.8', tone: 'ok' },
        { label: 'H6 · Recognition Not Recall', value: 1, score: '.4', tone: 'ok' },
        { label: 'H4 · Consistency & Standards', value: .6, score: '.2', tone: 'ok' },
      ],
      severity: {
        title: 'Severity distribution',
        caption: '85 checks rated 0 (no problem) to 4 (catastrophic).',
        items: [
          { label: '0 · Not a Problem', value: 100, count: '30', tone: 'ok' },
          { label: '1 · Cosmetic', value: 26.7, count: '8', tone: 'ok' },
          { label: '2 · Minor', value: 36.7, count: '11', tone: 'warn' },
          { label: '3 · Major', value: 70, count: '21', tone: 'warn' },
          { label: '4 · Catastrophic', value: 6.7, count: '2', tone: 'crit' },
        ],
      },
      passRate: {
        title: 'Pass rate by heuristic',
        caption: 'Share of checks passed within each heuristic.',
        items: [
          { label: 'H1 Visibility', value: 44, rate: '44%', tone: 'warn' },
          { label: 'H2 Real World', value: 60, rate: '60%', tone: 'warn' },
          { label: 'H3 Control', value: 33, rate: '33%', tone: 'crit' },
          { label: 'H4 Consistency', value: 100, rate: '100%', tone: 'ok' },
          { label: 'H5 Error Prev.', value: 50, rate: '50%', tone: 'warn' },
          { label: 'H6 Recognition', value: 83, rate: '83%', tone: 'ok' },
          { label: 'H7 Flexibility', value: 12, rate: '12%', tone: 'crit' },
          { label: 'H8 Aesthetic', value: 50, rate: '50%', tone: 'warn' },
          { label: 'H9 Recovery', value: 25, rate: '25%', tone: 'crit' },
          { label: 'H10 Help & Docs', value: 20, rate: '20%', tone: 'crit' },
        ],
      },
    },
  },
  insights: {
    eyebrow: 'Key insights',
    title: 'The Opportunity Wasn’t A Better Split—It Was Making Shared Expenses Explainable, Less Manual, And Less Personal',
    lead: 'Cross-method evidence narrowed the design space into four principles. They guided what we explored next—not predetermined feature decisions.',
    evidenceLabel: 'Evidence',
    principleLabel: 'Design principle',
    items: [
      { icon: 'proof', title: 'Proof Creates Confidence To Pay', evidence: '3 / 4 requested receipt support', insight: 'People need to understand a charge before they trust it.', principle: 'Keep receipts, notes, and itemization attached.' },
      { icon: 'flexibility', title: 'Flexibility Keeps Work Inside Dong', evidence: '4 / 4 reported manual work · H7 pass: 12%', insight: 'When a split cannot adapt, groups calculate elsewhere.', principle: 'Automate repetition while preserving organizer control.' },
      { icon: 'reminder', title: 'The System Should Carry The Ask', evidence: 'Users worried about pressuring friends', insight: 'Direct repayment reminders feel personal.', principle: 'Use neutral, system-mediated reminders.' },
      { icon: 'participation', title: 'Participation Needs Constraint Validation', evidence: 'Repeated across reviews and conversations', insight: 'Mixed Blu/non-Blu groups break at the participation boundary.', principle: 'Validate external settlement before designing it.' },
    ],
  },
  personas: {
    eyebrow: 'Personas',
    title: 'Sara Organizes The Split; Nick Needs To Trust It',
    lead: 'Sara and Nick carry the same friction from two sides of the shared-expense relationship.',
    goalLabel: 'Goal',
    painLabel: 'Pain points · High → Medium',
    items: [
      {
        index: '01',
        type: 'Primary persona',
        name: 'Sara',
        role: 'Organizer',
        image: { src: rebuildAsset('figma-exports/persona-sara-hd.png'), alt: 'Sara, organizer persona from the original case study' },
        behavior: 'Plans first, chases repayment',
        quote: 'I want everyone to pay their share easily — even if they don’t use Blu — without me having to remind anyone.',
        goal: 'Have Dong handle the tracking and reminders for her.',
        goalDetail: 'Right now she splits every shared expense by hand and chases each person herself.',
        pains: [
          'Lacks the ability to share payment receipts and expense breakdown details, creating concerns about potential confusion or disagreements among group members.',
          'Feels dissatisfied with spending time tracking and reminding others about their pending payments.',
          'Finds managing uneven expense splits time-consuming and frustrating.',
          'Faces difficulties collecting payments when some group members are not Blu users.',
        ],
      },
      {
        index: '02',
        type: 'Secondary persona',
        name: 'Nick',
        role: 'Payer',
        image: { src: rebuildAsset('figma-exports/persona-nick-hd.png'), alt: 'Nick, participant persona from the original case study' },
        behavior: 'Joins in, settles fast',
        quote: 'I want to see a clear breakdown of what I owe and why, so I can pay with confidence.',
        goal: 'See exactly what he owes, then pay it on time.',
        goalDetail: 'Right now he lacks visibility into expense details and relies on manual reminders to pay on time.',
        pains: [
          'Lacks transparency and supporting documentation to confidently trust recorded expenses.',
          'May forget to complete payments if the expense organizer does not send a reminder.',
          'Cannot provide feedback or raise questions about their share of expenses.',
        ],
      },
    ],
  },
  socialFriction: {
    eyebrow: 'The social friction problem',
    title: 'The Real Challenge Isn’t Splitting The Bill — It’s Asking For The Money.',
    lead: 'Unpaid debt can turn a product task into an interpersonal moment.',
    steps: [
      { title: 'Unpaid debt', body: 'A friend still owes money in the group.', image: { src: rebuildAsset('figma-exports/friction-1-hd.png'), alt: 'Original illustration of an anxious payment reminder moment' } },
      { title: 'Hesitation', body: 'The organizer worries that reminding them will feel pushy or transactional.', image: { src: rebuildAsset('figma-exports/friction-2-hd.png'), alt: 'Original illustration of hesitation before asking for repayment' } },
      { title: 'Personal chasing', body: 'Follow-up moves outside the product and into a direct personal ask.', image: { src: rebuildAsset('figma-exports/friction-3-hd.png'), alt: 'Original illustration of a nervous repayment message' } },
      { title: 'Relationship friction', body: 'Repeating this pattern can quietly wear on the relationship.', image: { src: rebuildAsset('figma-exports/friction-4-hd.png'), alt: 'Original illustration of relationship discomfort around debt' } },
    ],
    source: 'Based on user feedback patterns observed in comparable expense-splitting apps, and consistent with published research on interpersonal debt communication (Angulo, Goldstein & Norton, 2024, Journal of Consumer Psychology).',
  },
  journey: {
    eyebrow: 'Journey mapping',
    title: 'Trust Drops When Costs Become Manual, Unclear, And Personal',
    lead: 'One map of the whole Dong experience, synthesized across desk research, user interviews, and heuristic evaluation — not interview data alone.',
    arcLabel: 'Emotional arc for Sara and Nick across the current Dong journey',
    caption: 'Emotional Arc · Sara and Nick across the journey. Dashed segments show where a persona is not active in a step; red marks key opportunity points.',
    saraLabel: 'Sara · ',
    nickLabel: 'Nick · ',
    opportunityLabel: 'Opportunity',
    personas: [
      { name: 'Sara', role: 'Organizer', image: { src: rebuildAsset('figma-exports/persona-sara-hd.png'), alt: 'Sara persona' } },
      { name: 'Nick', role: 'Participant', image: { src: rebuildAsset('figma-exports/persona-nick-hd.png'), alt: 'Nick persona' } },
    ],
    columns: [
      { title: 'Set Up', sara: 'Starts a group for the shared expense and invites members.', nick: 'Joins the group through the invite link.', pains: ["Some intended members can't join without a Blu account."] },
      { title: 'Log & Split', sara: 'Manually logs each cost and splits the amount across the group.', nick: 'Not active in this step.', pains: ['Manual entry for every single cost adds up fast.', 'Uneven expenses require manual adjustment.', "Receipts and documentation can't be shared."] },
      { title: 'Track, Remind & Review', sara: "Shares the breakdown, tracks who's paid, and manually re-reminds unpaid members.", nick: "Reviews the charge assigned to him and decides whether it's correct before paying.", pains: ['Sara feels uncomfortable asking friends for money directly.', "Nick feels uncertain because receipts aren't attached."] },
      { title: 'Settling', sara: "Checks the group's debt/credit summary to see where payments and settlements stand.", nick: 'Completes the payment, Blu-to-Blu.', pains: ["Both see totals, but checking detail means opening transactions one by one."] },
    ],
    points: [
      { tone: 'sara', x: 12.5, y: 120, label: 'Sara · Frustrated', image: { src: rebuildAsset('figma-exports/emo-sara-frustrated-hd.png'), alt: 'Sara feels frustrated at setup' } },
      { tone: 'nick', x: 12.5, y: 52, label: 'Nick · Curious', image: { src: rebuildAsset('figma-exports/emo-nick-curious-hd.png'), alt: 'Nick feels curious at setup' } },
      { tone: 'sara', x: 37.5, y: 200, label: 'Sara · Overwhelmed', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-sara-overwhelmed-hd.png'), alt: 'Sara feels overwhelmed at log and split' } },
      { tone: 'sara', x: 62.5, y: 160, label: 'Sara · Uncomfortable', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-sara-uncomfortable-hd.png'), alt: 'Sara feels uncomfortable while reminding' } },
      { tone: 'nick', x: 62.5, y: 92, label: 'Nick · Uncertain', opportunity: true, image: { src: rebuildAsset('figma-exports/emo-nick-uncertain-hd.png'), alt: 'Nick feels uncertain while reviewing' } },
      { tone: 'sara', x: 81.5, y: 40, label: 'Sara · Relieved', image: { src: rebuildAsset('figma-exports/emo-sara-relieved-hd.png'), alt: 'Sara feels relieved after settlement' } },
      { tone: 'nick', x: 88.7, y: 40, label: 'Nick · Relieved', image: { src: rebuildAsset('figma-exports/emo-nick-relieved-hd.png'), alt: 'Nick feels relieved after settlement' } },
    ],
    tooltips: [
      { x: 12.5, y: 150, rows: [{ tone: 'sara', name: 'Sara', state: 'Frustrated' }, { tone: 'nick', name: 'Nick', state: 'Curious' }] },
      { x: 37.5, y: 232, rows: [{ tone: 'sara', name: 'Sara', state: 'Overwhelmed' }, { tone: 'nick', name: 'Nick', state: 'not involved', muted: true }] },
      { x: 62.5, y: 192, rows: [{ tone: 'sara', name: 'Sara', state: 'Uncomfortable' }, { tone: 'nick', name: 'Nick', state: 'Uncertain' }] },
      { x: 85, y: 72, rows: [{ tone: 'sara', name: 'Sara', state: 'Relieved' }, { tone: 'nick', name: 'Nick', state: 'Relieved' }] },
    ],
    legend: [
      { tone: 'sara', label: 'Sara' },
      { tone: 'nick', label: 'Nick' },
      { tone: 'inactive', label: 'Dashed = not involved' },
      { tone: 'opportunity', label: 'Opportunity = key friction / intervention point' },
    ],
  },
  opportunity: {
    eyebrow: 'Opportunity',
    title: 'From Evidence To Opportunity',
    label: 'How might we',
    question: 'How might Dong help groups document, split, and settle shared expenses with less manual effort and less social pressure?',
    body: 'This framing is derived from the recovered problem statement and converging research themes.',
  },
  prioritization: {
    matrix: {
      kicker: 'Prioritization',
      title: 'Four Priorities Shaped Three Product Capabilities',
      body: 'Receipt OCR, itemized splitting, reminder support, and automatic-payment exploration moved forward. OCR and itemized splitting combine into one end-to-end capability; non-Blu participation remains a documented scope decision.',
      asset: {
        src: rebuildAsset('figma-exports/impact-effort-matrix-figma.png'),
        lightSrc: rebuildAsset('figma-exports/impact-effort-matrix-en-light.png'),
        alt: 'Impact effort matrix exported from Figma node 721:24251',
      },
      focus: ['Receipt Scan / OCR', 'Flexible and itemized splitting', 'Reminder support', 'Automatic-payment exploration'],
    },
    selectedLabel: 'Selected priorities',
    selected: ['Receipt OCR', 'Itemized Split', 'Reminder Support', 'Automatic Payment'],
    nonBluDecision: {
      kicker: 'Product / scope decision',
      title: "Why we didn't design for non-Blu participation",
      body: 'We identified the barrier, but kept it outside the redesign scope. A plausible solution would mostly sit outside the in-app Dong flow: generate a debt/payment link or QR for the amount and share it through SMS or a link. Opening participation to non-Blu users could also conflict with BluBank’s likely acquisition incentives, so this opportunity was documented but not prioritized for the redesign.',
    },
  },
  productDirection: {
    eyebrow: 'Proposed product direction',
    title: 'From Priorities To Product Capabilities',
    lead: 'Four selected priorities became three proposed capabilities because receipt OCR and itemized splitting work as one connected flow. These are proposals, not current BluBank Dong features.',
    items: [
      {
        title: 'Receipt OCR',
        currentLabel: 'Current Dong',
        current: 'Transaction creation relies on amount entry and manual or equal share assignment.',
        gapLabel: 'Identified gap',
        gap: 'The product does not transform receipts into structured expenses or support item-level allocation.',
        proposedLabel: 'Proposed experience',
        proposed: 'Receipt scanning, OCR extraction, editable item review, discrepancy handling, and itemized member breakdown.',
      },
      {
        title: 'Reminder system',
        currentLabel: 'Current Dong',
        current: 'Outstanding transactions may require organizer follow-up and can expose manual individual reminders.',
        gapLabel: 'Identified gap',
        gap: 'There is no centralized reminder management, scheduling, recurrence, or richer reminder workflow.',
        proposedLabel: 'Proposed experience',
        proposed: 'A system-supported reminder experience designed to reduce interpersonal pressure and clarify settlement state.',
      },
      {
        title: 'Automatic Payment',
        currentLabel: 'Current Dong',
        current: 'Settlement depends on participants completing payment themselves.',
        gapLabel: 'Identified gap',
        gap: 'There is no automatic settlement rule for recurring or low-friction shared expenses.',
        proposedLabel: 'Proposed experience',
        proposed: 'Opt-in Automatic Payment with explicit activation, amount cap, consent, notification, clear status, and easy deactivation.',
      },
    ],
  },
  firstDesign: {
    eyebrow: 'Initial concepts',
    title: 'Design Concepts Turned Research Friction Into Flows',
    lead: 'Prioritization selected three capability areas to explore: receipt intelligence, reminder support, and Automatic Payment.',
    flows: [
      { title: 'Receipt Scan / OCR', hypothesis: 'If receipt details can be extracted and assigned clearly, payers can understand what they owe without extra explanation.', asset: mediaSet([figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }), figmaSlot('figma-ocr-edited-items.png', { node: '684:18532' }), figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' })], 'Concept exploration: extraction, editing, and discrepancy handling.') },
      { title: 'Reminder', hypothesis: 'If repayment follow-up feels system-supported, organizers can reduce awkward personal chasing.', asset: mediaSet([figmaSlot('figma-reminder-list.png', { node: '684:13311' }), figmaSlot('figma-reminder-schedule.png', { node: '684:13729' }), figmaSlot('figma-reminder-message.png', { node: '684:13859' })], 'Concept exploration: recipient selection, scheduling, and message review.') },
      { title: 'Automatic Payment', hypothesis: 'If repeated settlement steps can be simplified, groups may complete repayment with less manual effort.', asset: mediaSet([figmaSlot('figma-autopay-settings-entry.png', { node: '684:12288' }), figmaSlot('figma-autopay-limit.png', { node: '684:12380' }), figmaSlot('figma-autopay-refined.png', { node: '684:12480' })], 'Concept exploration: opt-in, amount limit, and active-state clarity.') },
    ],
  },
  feedback: {
    eyebrow: 'User feedback',
    title: 'User Feedback Exposed Three Clarity Gaps',
    lead: 'Three actionable findings from the Refactor notes shaped the final iteration.',
    items: [
      { feedbackLabel: 'User said', feedback: 'The completed reminder option was unclear: it did not communicate whether the debt was settled or only the reminder cycle had ended. Translated from Persian.', learnedLabel: 'What we learned', learned: 'Reminder status and debt status need to be visually and verbally distinct.', responseLabel: 'Design response', response: 'Clarify status language and separate reminder completion from settlement completion.' },
      { feedbackLabel: 'User said', feedback: 'The amount should be editable in an input too, not only controlled by a slider. Translated from Persian.', learnedLabel: 'What we learned', learned: 'A slider alone is not precise enough for a financial limit.', responseLabel: 'Design response', response: 'Add direct numeric input alongside the slider for exact control.' },
      { feedbackLabel: 'User said', feedback: 'The switch should be on when the feature is active and turn off when disabled. Translated from Persian.', learnedLabel: 'What we learned', learned: 'The toggle must follow the conventional ON/OFF mental model.', responseLabel: 'Design response', response: 'Align the automatic-payment switch with standard active/inactive behavior.' },
    ],
  },
  iteration: {
    eyebrow: 'Iteration',
    title: 'Each Iteration Turned Feedback Into A Clearer Control',
    lead: 'This is first design → user feedback → refined design, not existing BluBank → redesign.',
    beforeLabel: 'Before',
    afterLabel: 'After',
    items: [
      { title: 'Precise payment limit', v1: mediaSet([figmaSlot('figma-feedback-amount-before.png', { node: '684:15732' })]), v2: mediaSet([figmaSlot('figma-feedback-amount-after.png', { node: '684:15789' })]), issueLabel: 'User feedback', issue: 'A slider alone did not provide enough precision for a financial limit.', changeLabel: 'Design response', change: 'Allow direct numeric entry alongside the slider and clarify the label.' },
      { title: 'A clearer toggle mental model', v1: mediaSet([figmaSlot('figma-feedback-toggle-before.png', { node: '684:15996' })]), v2: mediaSet([figmaSlot('figma-feedback-toggle-after.png', { node: '684:16124' })]), issueLabel: 'User feedback', issue: 'The negative “Disable Automatic Payment” control reversed the expected switch mental model.', changeLabel: 'Design response', change: 'Use a positive “Automatic Payment” label: ON = active, OFF = inactive.' },
      { title: 'Clear reminder status', v1: mediaSet([figmaSlot('figma-feedback-reminder-before.png', { node: '684:16641' })]), v2: mediaSet([figmaSlot('figma-feedback-reminder-after.png', { node: '684:16729' })]), issueLabel: 'User feedback', issue: '“Completed reminder” did not clearly communicate whether the debt was settled or only the reminder process had ended.', changeLabel: 'Design response', change: 'Separate debt status from reminder status so completion is unambiguous.' },
    ],
  },
  ocrDecision: {
    eyebrow: 'Design decision',
    title: 'OCR Needed Automation With Human Control',
    lead: 'The OCR flow is a product-design rationale, not a fabricated feedback problem.',
    kicker: 'Receipt Scan / OCR',
    body: 'OCR can reduce manual entry, but financial flows still need review, correction, and explicit confirmation.',
    carouselLabel: 'Receipt OCR design decision screens',
    slides: [
      { src: './assets/figma-exports/design-decision-en-01.png', alt: 'Extracted receipt items ready for review' },
      { src: './assets/figma-exports/design-decision-en-02.png', alt: 'Invoice amount mismatch warning with correction options' },
      { src: './assets/figma-exports/design-decision-en-03.png', alt: 'Percentage-based share assignment for a receipt item' },
      { src: './assets/figma-exports/design-decision-en-04.png', alt: 'Receipt items assigned to group members' },
      { src: './assets/figma-exports/design-decision-en-05.png', alt: 'Final member share summary before confirmation' },
    ],
    asset: mediaSet([
      figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }),
      figmaSlot('figma-ocr-edited-items.png', { node: '684:18532' }),
      figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' }),
      figmaSlot('figma-ocr-final-breakdown.png', { node: '684:19614' }),
    ], 'OCR decision flow: extract, edit, resolve discrepancy, confirm breakdown.'),
    points: [
      'OCR extracts receipt items and prices.',
      'Users review detected data and can edit, delete, or manually add items.',
      'The system compares edited item totals with the original receipt amount.',
      'If totals diverge, a discrepancy warning lets users correct items or intentionally continue.',
      'Before submission, users see each member’s share and can attach the receipt to the Dong transaction.',
    ],
  },
  finalExperience: {
    eyebrow: 'Final experience',
    title: 'The Final Experience Makes Shared Expenses Documented, Flexible, And System-supported',
    lead: 'Three proposed flows carry the redesign: OCR, neutral reminders, and opt-in Automatic Payment.',
    ariaLabel: 'Final experience flows',
    items: [
      { shortTitle: 'Receipt OCR', title: 'Final Flow 01 — Receipt OCR', outcome: 'Scan → Extract → Review → Assign → Confirm.', annotations: ['Receipt evidence stays attached.', 'Detected items remain editable.', 'The final split is confirmed before sharing.'], asset: mediaSet([figmaSlot('figma-ocr-extracted-items.png', { node: '684:18461' }), figmaSlot('figma-ocr-discrepancy.png', { node: '684:18607' }), figmaSlot('figma-ocr-final-breakdown.png', { node: '684:19614' })], 'OCR turns a receipt into an editable, explainable group split.', 'final-ocr-flow-en.mp4') },
      { shortTitle: 'Reminder', title: 'Final Flow 02 — Reminder', outcome: 'Centralized follow-up with scheduling, editable messages, and visible status history.', annotations: ['Recipient selection is centralized.', 'Reminders can be scheduled or recurring.', 'Message and history stay editable and visible.'], asset: mediaSet([figmaSlot('figma-reminder-list.png', { node: '684:13311' }), figmaSlot('figma-reminder-schedule.png', { node: '684:13729' }), figmaSlot('figma-reminder-message.png', { node: '684:13859' })], 'System-supported reminders reduce direct personal chasing.', 'final-reminder-flow-en.mp4') },
      { shortTitle: 'Automatic Payment', title: 'Final Flow 03 — Automatic Payment', outcome: 'Opt-in settlement support with clear consent, caps, status, and easy deactivation.', annotations: ['Explicit opt-in and configurable cap.', 'Positive ON/OFF mental model.', 'System feedback confirms the state.'], asset: mediaSet([figmaSlot('figma-autopay-settings-entry.png', { node: '684:12288' }), figmaSlot('figma-autopay-limit.png', { node: '684:12380' }), figmaSlot('figma-autopay-refined.png', { node: '684:12480' })], 'Automatic Payment remains opt-in, capped, and reversible.', 'final-auto-payment-flow-en.mp4') },
    ],
  },
  comparison: {
    eyebrow: 'Before / after',
    title: 'From Manual Coordination To Supported Settlement',
    lead: 'The redesign moves shared-expense management from memory, manual entry, and personal follow-up toward documented expenses, transparent splits, and system-supported settlement.',
    beforeLabel: 'Before',
    afterLabel: 'Proposed experience',
    arrow: '→',
    before: ['Manual entry', 'Opaque charges', 'Organizer-driven follow-up'],
    after: ['Receipt evidence', 'Editable itemized split', 'System-supported settlement'],
  },
  measurement: {
    eyebrow: 'Measurement',
    title: 'How Success Would Be Measured',
    lead: 'Because the concept has not been launched, these metrics define how its effectiveness should be evaluated—not claimed outcomes.',
    signalLabel: 'Signal',
    methodLabel: 'Method',
    items: [
      { title: 'OCR Accuracy & Correction', signal: 'Organizers successfully review and correct extracted receipt items before sharing.', method: 'Task-based usability test' },
      { title: 'Split Comprehension', signal: 'Payers can correctly explain what they owe and why.', method: 'Comprehension check' },
      { title: 'Reminder Experience', signal: 'Reminders feel clear, neutral, and non-confrontational.', method: 'Post-task rating' },
      { title: 'Automatic Payment Trust', signal: 'Users understand caps, status, and deactivation controls.', method: 'Trust and control assessment' },
    ],
  },
  reflection: {
    eyebrow: 'Reflection',
    title: 'What I Learned—And What Comes Next',
    lead: 'The work closes with the design principles that shaped the proposal and the questions that still need validation.',
    learnedLabel: 'What I learned',
    nextLabel: 'What I would validate next',
    learned: [
      { title: 'Shared Money Is Social', body: 'Designing the calculation is only part of the problem; the experience must also protect trust between people.' },
      { title: 'Evidence Creates Confidence', body: 'Receipts, notes, and itemization help participants understand and verify shared expenses.' },
      { title: 'Automation Needs Visible Control', body: 'Reminders and automatic payments feel safer when users can review, edit, limit, or deactivate them.' },
    ],
    next: [
      { title: 'Test The End-to-end Flow', body: 'Validate the complete OCR-to-settlement journey with both organizers and payers.' },
      { title: 'Validate Reminder Tone', body: 'Test reminder language within real group relationships and different levels of financial sensitivity.' },
      { title: 'Confirm Product Constraints', body: 'Clarify technical and regulatory constraints for automatic payments and non-Blu participants.' },
    ],
  },
};
